### PR TITLE
Update Strman.java

### PR DESCRIPTION
**Pull request by lizho**
fixed bug in between()
**Code:**
```
String s = "zzz[aa]zz[bbb]zz[cccc]zz[ddddd]z123456z";
Arrays.stream(between(s, "[", "]")).forEach(System.out::println);
```
**Result, before:**
> aa
> bbb
> cccc
> ddddd
> _z123456z_

**Result, after:**
> aa
> bbb
> cccc
> ddddd

**Code:**
```
String s = "zzz[[[aa]zz[[[bbb]zz[[[cccc]zz[[[ddddd]z123456z";
Arrays.stream(between(s, "[[[", "]")).forEach(System.out::println);
```
**Result, before:**
> aa
> bbb
> cccc
> ddddd
> _23456z_

**Result, after:**
> aa
> bbb
> cccc
> ddddd

### CODE REVIEW

**Comment by shekhargulati** [comment]
@lizho Can you please add test cases as well? Also, one of the existing test failed with your changes. Can you have a look?

**Comment by lizho** [comment]
It's perhaps just a logic issue.
```
    @Test
    public void between_shouldReturnFullStringWhenStartAndEndDoesNotExist() throws Exception {
        assertThat(between("[abc][def]", "{", "}"), arrayContaining("[abc][def]"));
        assertThat(between("", "{", "}"), arrayContaining(""));
    }
```
I thought between() might return an empty string when start and end does not exist. Otherwise, how can I differentiate cases below.

```
between("[abc]", "[", "]");
between("abc", "[", "]");
//both result are ["abc"]
```

**Comment by shekhargulati** [comment]
@lizho can you add test cases?

**Comment by lizho** [comment]
@shekhargulati sure,  test case updated.

**Pull request merged**
